server:
  port:8080

# Redis cache config 
spring:
  cache:
    type: redis
  redis:
    host: redis-forum-api
    port: 6379

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-forum-api:3306/forum
    username: forum
    password: Bk55yc1u0eiqga6e

# jpa
  jpa:
    database : MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true

# jwt
forum:
  jwt:
    secret: rm'!@N:Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D]):><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<:c38:>L/zBq`}C6tT*cCSVC^c]-L}&/
    expiration: 86400000

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java.version: @java.version@

management:
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    tags:
      application: app-forum-api
    distribution:
      sla:
        http:
          server:
            requests: 10ms,20ms,30ms,40ms,50ms,100ms,200ms,300ms,400ms,500ms,1s
      slo:
        http:
          server:
            requests: 10ms,20ms,30ms,40ms,50ms,100ms,200ms,300ms,400ms,500ms,1s
