{
 "title": "Dash Forum API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API BASIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "START TIME",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USER LOGGED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_success_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDBC  POOL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONNECTION STATE",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_active{application=\"$application\", instance=\"$instance\", pool=\"HikariPool-1\"}[$__range])",
     "legendFormat": "ACTIVE"
    },
    {
     "expr": "increase(hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", pool=\"HikariPool-1\"}[10m])",
     "legendFormat": "IDLE"
    },
    {
     "expr": "increase(hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", pool=\"HikariPool-1\"}[10m])",
     "legendFormat": "PENDING"
    }
   ]
  },
  {
   "title": "UPTIME TIME",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERRORS AT LOGIN",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_error_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONNECTION TIMEOUT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "REQUESTS TOTAL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos\"}[1m]))",
     "legendFormat": "/topicos"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos/{id}\"}[1m]))",
     "legendFormat": "/topicos/{id}"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/auth\"}[1m]))",
     "legendFormat": "/auth"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos\"}[1m])",
     "legendFormat": "{{method}} - {{uri}}: {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m])",
     "legendFormat": "{{method}} - {{uri}}: {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m])",
     "legendFormat": "{{method}} - {{uri}}: {{status}}"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri!=\"//actuator/prometheus\"}",
     "legendFormat": "{{method}} - {{uri}}: {{status}}"
    }
   ]
  },
  { "title": "API USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "HEAP USED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"heap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "Load Average 1m"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "NOHEAP USED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"nonheap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}