FROM openjdk:17-jdk-alpine

RUN addgroup -S spring && adduser -S spring -G spring

USER spring:spring

ARG JAR_FILE=target/*jar
COPY ${JAR_FILE} app.jar
ENV SPRING_PROFILES_ACTIVE="prod"

ENTRYPOINT ["java", "-jar", "/app.jar"]
